import Head from "next/head";
import React, { useRef, useState,useEffect } from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import AOS from "aos";
import "aos/dist/aos.css";


// import required modules
import { FreeMode, Pagination } from "swiper";
import Image from "next/image";
import NavBar from "../Components/NavBar";
import Script from "next/script";

import SA from "../styles/images/sa-min.jpg";
import computing from "../styles/images/user-computing.jpg";
import enterprise from "../styles/images/enterprise-computing.png";
import software from "../styles/images/software.png";
import swa from "../styles/images/swa-min.jpg";
import min from "../styles/images/-min1.jpg";

import Solor from '../styles/images/solar.jpg'
import Attendence from '../styles/images/attendence.jpg'
import Printer from '../styles/images/printer.jpg'
import AIO from '../styles/images/aioscanner.jpg'
import PhotoMachine from '../styles/images/photocopier.jpg'
import Grid from '../styles/images/2.jpg';
import Energy from '../styles/images/649853.png';
import UPS from '../styles/images/558385.png';
import Generator from '../styles/images/3118354.png'
import Icon from '../styles/images/709605.png'
import Clentt1 from '../styles/images/client5.jpg';
import Clentt2 from '../styles/images/client7.jpg';
import Clentt3 from '../styles/images/client8.png';
import Clentt4 from '../styles/images/client13.png';
import Clentt5 from '../styles/images/client14.jpg';
import Clentt6 from '../styles/images/client7.jpg';
import Clentt7 from '../styles/images/client14.jpg';

import ContactForm from "../Components/ContactForm";
import CEO from "../Components/CEO";
import Clients from "../Components/Clients";
import { Lines } from "react-preloaders";
import Loader from "../Components/Loader";









export default function Home() {
	const [loading, setloading] = useState(false)
	useEffect(() => {
		setloading(true);
		setTimeout(() => {
			setloading(false);
		}, 10000);
	}, []);

	
	
	
	return (
		<div>
			<Head>
				<title>USS ENTERPRISES</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Script
				className="u-script"
				type="text/javascript"
				src="../Components/jquery.js"
			/>
			<Script
				className="u-script"
				type="text/javascript"
				src="../Components/nicepage.js"
			/>
			{loading ? (
				<Loader/>
				// <Lines/>
			) : (
				<div
					className="u-body u-overlap u-overlap-contrast u-overlap-transparent u-xl-mode"
					data-lang="en"
				>
					<section
						className="u-align-left u-clearfix u-image u-shading u-section-1"
						id="carousel_5ad0"
						data-image-width="1782"
						data-image-height="1080"
					>
						<NavBar />
						<div className="u-clearfix u-sheet u-sheet-1">
							<h1 className="u-align-left u-text u-text-palette-3-base u-text-1">
								<b>USS ENTERPRISES</b>
							</h1>
							<h2 className=" u-text-2">
								<b>an ICT solution c​ompany</b>

								<br />
							</h2>
							<p className="u-text u-text-body-alt-color u-text-3">
								USS Enterprises is one of the fastest emerging IT Solution
								provider serving in IT industry since 2015 with a wide range of
								our{" "}
								<b>
									<i>
										“
										<span className="u-text-palette-3-base">
											Products and Services Portfolio.
										</span>
									</i>
								</b>
							</p>
							<a
								href="tel:+92-21-34390018"
								className="u-active-white u-border-2 u-border-hover-white u-border-white u-btn u-button-style u-hover-white u-none u-text-active-black u-text-body-alt-color u-text-hover-palette-1-base u-btn-1"
							>
								Call Now
							</a>
							<p className="u-text u-text-body-alt-color u-text-4">
								Consultancy with Excellency.
							</p>
						</div>
					</section>
					<section
						className="u-align-right u-clearfix u-grey-5 u-section-2"
						id="sec-227e"
						data-aos="fade-in"
					>
						<div className="u-clearfix u-sheet u-valign-middle u-sheet-1">
							<div className="u-container-style u-expanded-width-xs u-group u-image u-image-tiles u-image-1">
								<div className="u-container-layout u-container-layout-1"></div>
							</div>
							<div className="u-expanded-width-xs u-image u-image-default u-image-2">
								<Image src={SA} alt="" />
							</div>
							<div className="u-list u-list-1">
								<div className="u-repeater u-repeater-1">
									<div className="u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-1">
										<div className="u-container-layout u-similar-container u-valign-top u-container-layout-2">
											<span className="u-icon u-icon-circle u-palette-1-base u-icon-1">
												<svg
													className="u-svg-link"
													viewBox="0 0 511.986 511.986"
													xmlnsXlink="http://www.w3.org/1999/xlink"
													xlinkHref="#svg-f35c"
												></svg>
												<svg
													className="u-svg-content"
													viewBox="0 0 511.986 511.986"
													id="svg-f35c"
												>
													<path d="m496.986 370.039c8.284 0 15-6.716 15-15v-70.686c0-8.284-6.716-15-15-15h-25.507v-40.686h5.254c8.284 0 15-6.716 15-15v-70.686c0-8.284-6.716-15-15-15h-146.838c-17.964-73.052-84.014-127.404-162.531-127.404-92.285 0-167.364 75.079-167.364 167.364s75.079 167.364 167.364 167.364c26.047 0 50.721-5.984 72.726-16.644v21.378h-5.254c-8.284 0-15 6.716-15 15v70.685c0 8.284 6.716 15 15 15h5v55.686c0 8.284 6.716 15 15 15h241.897c8.284 0 15-6.716 15-15v-70.686c0-8.284-6.716-15-15-15h-5v-40.685zm-55.507-100.685h-141.071c9.424-12.334 17.178-26.007 22.914-40.686h118.158v40.686zm20.254-111.372v40.686h-129.843c1.857-9.964 2.838-20.233 2.838-30.727 0-3.344-.11-6.662-.305-9.958h127.31zm-431.733 9.959c0-75.743 61.622-137.364 137.364-137.364s137.364 61.621 137.364 137.364-61.621 137.364-137.364 137.364-137.364-61.621-137.364-137.364zm240.09 132.036c.267-.208.534-.414.8-.623h211.097v40.686h-211.897zm211.643 181.433h-211.897v-40.686h211.897zm-20-70.686h-206.897-5v-40.685h5.254 206.643z"></path>
													<path d="m216.944 157.295c6.122-8.188 9.752-18.343 9.752-29.331 0-25.461-19.489-46.449-44.331-48.847v-21.45c0-8.284-6.716-15-15-15s-15 6.716-15 15v21.216h-17.775c-8.284 0-15 6.716-15 15v68.203.11 79.801c0 3.99 1.589 7.815 4.417 10.63 2.812 2.799 6.617 4.37 10.583 4.37h.067c.176-.001 8.062-.036 17.707-.074v21.29c0 8.284 6.716 15 15 15s15-6.716 15-15v-21.389c1.052-.002 1.984-.003 2.763-.003 30.254 0 54.868-24.614 54.868-54.868.001-18.398-9.112-34.698-23.051-44.658zm-39.33-48.411c10.521 0 19.082 8.56 19.082 19.081s-8.56 19.081-19.082 19.081c-3.169 0-9.179.017-15.723.041h-12.3v-38.203zm7.513 117.938c-6.462 0-23.092.062-35.537.113v-49.801c3.963-.016 8.28-.033 12.386-.047h23.151c13.712 0 24.868 11.156 24.868 24.868s-11.155 24.867-24.868 24.867z"></path>
												</svg>
											</span>
											<h4 className="u-align-center u-text u-text-1">
												<b>
													<i>
														ACER<span></span>
													</i>
												</b>
											</h4>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-2">
										<div className="u-container-layout u-similar-container u-valign-top u-container-layout-3">
											<span className="u-icon u-icon-circle u-palette-1-base u-icon-2">
												<svg
													className="u-svg-link"
													viewBox="0 0 24 24"
													xmlnsXlink="http://www.w3.org/1999/xlink"
													xlinkHref="#svg-2d93"
												></svg>
												<svg
													className="u-svg-content"
													viewBox="0 0 24 24"
													id="svg-2d93"
												>
													<path d="m19.75 4.687c-.191 0-.382-.072-.528-.218-1.93-1.914-4.495-2.969-7.222-2.969s-5.292 1.055-7.222 2.969c-.294.292-.768.29-1.061-.004-.292-.294-.29-.77.004-1.061 2.214-2.195 5.154-3.404 8.279-3.404s6.065 1.209 8.278 3.404c.294.291.296.767.004 1.061-.146.147-.339.222-.532.222z"></path>
													<path d="m17.052 7.362c-.191 0-.382-.072-.528-.218-1.211-1.201-2.817-1.862-4.524-1.862s-3.313.661-4.524 1.863c-.294.292-.769.29-1.061-.004-.291-.294-.29-.769.004-1.061 1.494-1.481 3.476-2.298 5.581-2.298s4.087.816 5.581 2.298c.294.292.296.767.004 1.061-.147.147-.34.221-.533.221z"></path>
													<path d="m14.354 10.038c-.193 0-.386-.074-.533-.222-.963-.971-2.681-.971-3.644 0-.291.294-.765.296-1.06.004-.294-.291-.296-.766-.004-1.06.765-.772 1.791-1.197 2.887-1.197s2.122.425 2.887 1.196c.292.294.29.77-.004 1.061-.147.146-.338.218-.529.218z"></path>
													<path d="m9.125 21h-1.875c-.414 0-.75-.336-.75-.75s.336-.75.75-.75h1.875c.482 0 .875-.393.875-.875s-.393-.875-.875-.875h-1.875c-.414 0-.75-.336-.75-.75v-3.25c0-.414.336-.75.75-.75h3.5c.414 0 .75.336.75.75s-.336.75-.75.75h-2.75v1.75h1.125c1.31 0 2.375 1.065 2.375 2.375s-1.065 2.375-2.375 2.375z"></path>
													<path d="m16.75 21h-2.5c-.965 0-1.75-.785-1.75-1.75v-4.5c0-.965.785-1.75 1.75-1.75h2.5c.414 0 .75.336.75.75s-.336.75-.75.75h-2.5c-.138 0-.25.112-.25.25v4.5c0 .138.112.25.25.25h1.75v-1.5h-.75c-.414 0-.75-.336-.75-.75s.336-.75.75-.75h1.5c.414 0 .75.336.75.75v3c0 .414-.336.75-.75.75z"></path>
												</svg>
											</span>
											<h4 className="u-text u-text-2">
												<b>
													<i>LENOVO</i>
												</b>
											</h4>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-3">
										<div className="u-container-layout u-similar-container u-valign-top u-container-layout-4">
											<span className="u-icon u-icon-circle u-palette-1-base u-icon-3">
												<svg
													className="u-svg-link"
													viewBox="0 0 512.012 512.012"
													xmlnsXlink="http://www.w3.org/1999/xlink"
													xlinkHref="#svg-bcdb"
												></svg>
												<svg
													className="u-svg-content"
													viewBox="0 0 512.012 512.012"
													id="svg-bcdb"
												>
													<path d="m59.998 332.666v87.346h61v92h210v-62.218c0-56.303 12.309-115.303 37.563-179.782h32.224l25.611 25.611c-2.817 5.875-4.398 12.451-4.398 19.39 0 24.813 20.187 45 45 45s45-20.187 45-45-20.187-45-45-45c-6.938 0-13.514 1.581-19.389 4.398l-34.398-34.398h-32.572c3.497-9.779 6.115-19.796 7.843-30.01h36.096c6.192 17.469 22.865 30.01 42.42 30.01 24.813 0 45-20.187 45-45s-20.187-45-45-45c-19.555 0-36.228 12.541-42.42 30h-33.58c0-10.152-.845-20.177-2.485-30h24.698l34.398-34.397c5.875 2.817 12.45 4.398 19.389 4.398 24.813 0 45-20.187 45-45s-20.187-45-45-45-45 20.187-45 45c0 6.939 1.581 13.514 4.398 19.389l-25.611 25.61h-19.994c-24.022-68.126-88.986-119.066-167.616-120-88.723-1.043-163.221 61.684-179.498 143.168-5.685 28.455-4.837 56.601 2.51 83.77l-36.173 62.25zm407-32.654c8.271 0 15 6.729 15 15s-6.729 15-15 15-15-6.729-15-15 6.728-15 15-15zm0-120c8.271 0 15 6.729 15 15s-6.729 15-15 15-15-6.729-15-15 6.728-15 15-15zm0-120c8.271 0 15 6.729 15 15s-6.729 15-15 15-15-6.729-15-15 6.728-15 15-15zm-117.798 178.089c-.272.639-.533 1.273-.802 1.911h-92.44c6.565-8.725 11.274-18.921 13.531-30.01h88.481c-1.971 9.61-4.896 18.996-8.77 28.099zm-108.202-43.089c0 24.813-20.187 45-45 45s-45-20.187-45-45 20.187-45 45-45 45 20.187 45 45zm120-15h-91.509c-2.258-11.079-6.967-21.275-13.532-30h101.998c1.993 9.704 3.043 19.738 3.043 30zm-297.903-30.954c13.953-69.845 76.913-119.906 149.725-119.047 60.427.717 112.514 37.715 135.55 90.001h-152.372c-41.355 0-75 33.645-75 75s33.645 75 75 74.99h140.455c-23.819 63.823-35.455 122.919-35.455 179.792v32.218h-150v-92h-61v-72.655l-50.417-36.534 29.076-50.038c-.795-4.156-14.724-35.852-5.562-81.727z"></path>
													<path d="m180.998 180.012h30v30h-30z"></path>
												</svg>
											</span>
											<h4 className="u-text u-text-3">MICROSOFT</h4>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-4">
										<div className="u-container-layout u-similar-container u-valign-top u-container-layout-5">
											<span className="u-icon u-icon-circle u-palette-1-base u-icon-4">
												<svg
													className="u-svg-link"
													viewBox="0 0 512 512"
													xmlnsXlink="http://www.w3.org/1999/xlink"
													xlinkHref="#svg-1006"
												></svg>
												<svg
													className="u-svg-content"
													viewBox="0 0 512 512"
													id="svg-1006"
												>
													<path d="m467.5 218.79c5.523 0 10-4.477 10-10s-4.477-10-10-10h-37.882v-27.225h37.882c5.523 0 10-4.477 10-10s-4.477-10-10-10h-37.882v-16.361c0-2.651-1.052-5.193-2.926-7.068l-28.917-28.941c-1.875-1.877-4.42-2.932-7.074-2.932h-16.365v-37.848c0-5.523-4.477-10-10-10s-10 4.477-10 10v37.848h-27.23v-37.848c0-5.523-4.477-10-10-10s-10 4.477-10 10v37.848h-27.202v-35.836c0-33.32-27.11-60.427-60.434-60.427-27.264 0-50.959 18.428-58.186 44.029-20.782 2.112-40.037 11.3-54.896 26.343-16.78 16.99-26.021 39.501-26.021 63.386 0 11.853 2.34 23.593 6.827 34.476-14.037 7.459-26.081 18.186-35.211 31.443-11.437 16.608-17.483 36.079-17.483 56.309 0 37.241 20.362 70.644 52.689 87.78-4.482 10.863-6.82 22.593-6.82 34.448 0 23.885 9.241 46.396 26.021 63.386 14.858 15.043 34.113 24.231 54.895 26.343 7.226 25.618 30.923 44.057 58.187 44.057 33.323 0 60.434-27.107 60.434-60.427v-35.864h27.202v37.876c0 5.523 4.477 10 10 10s10-4.477 10-10v-37.876h27.23v37.876c0 5.523 4.477 10 10 10s10-4.477 10-10v-37.876h16.365c2.652 0 5.195-1.053 7.071-2.929l28.917-28.913c1.875-1.875 2.929-4.419 2.929-7.071v-16.39h37.88c5.523 0 10-4.477 10-10s-4.477-10-10-10h-37.882v-27.196h37.882c5.523 0 10-4.477 10-10s-4.477-10-10-10h-37.882v-27.224h37.882c5.523 0 10-4.477 10-10s-4.477-10-10-10h-37.882v-27.196zm-248.028 273.21c-16.589 0-31.194-10.201-37.343-24.932 7.294-1.306 14.406-3.525 21.245-6.663 9.939-4.563 18.828-10.808 26.419-18.562 3.863-3.947 3.796-10.278-.15-14.142-3.947-3.863-10.277-3.796-14.142.15-5.875 6-12.762 10.837-20.469 14.375-8.144 3.736-16.776 5.807-25.659 6.167-38.072-.628-69.004-32.056-69.004-70.182 0-12.047 3.095-23.917 8.95-34.329 1.412-2.509 1.673-5.505.717-8.22-.955-2.716-3.035-4.888-5.706-5.961-30.27-12.157-49.83-41.093-49.83-73.715 0-32.631 19.557-61.555 49.824-73.686 5.946-3.215 7.613-7.941 5.001-14.175-5.859-10.442-8.956-22.326-8.956-34.366 0-38.126 30.932-69.554 69.004-70.182 8.827.359 17.466 2.432 25.657 6.166 7.721 3.544 14.603 8.385 20.456 14.389 1.96 2.01 4.56 3.02 7.162 3.02 2.516 0 5.035-.944 6.979-2.839 3.955-3.855 4.035-10.187.18-14.141-7.576-7.771-16.47-14.031-26.458-18.616-6.86-3.127-13.962-5.341-21.221-6.646 6.149-14.719 20.754-24.91 37.344-24.91 22.295 0 40.434 18.136 40.434 40.427v122.603h-31.132l-26.531-26.528c2.824-5.155 4.33-10.963 4.33-17.004 0-9.476-3.69-18.385-10.393-25.086-13.832-13.83-36.34-13.831-50.173 0-6.701 6.701-10.392 15.61-10.392 25.085s3.69 18.384 10.392 25.085c6.916 6.915 16.001 10.373 25.086 10.373 5.86 0 11.716-1.448 16.995-4.325l29.472 29.469c2.133 1.909 4.49 2.886 7.071 2.929h35.274v42.956h-62.667c-4.332-14.694-17.948-25.455-34.039-25.455-19.552 0-35.458 15.905-35.458 35.455 0 19.565 15.906 35.483 35.458 35.483 16.094 0 29.712-10.773 34.041-25.483h62.665v42.956h-35.274c-.268 0-.498.014-.71.034-2.318.164-4.591 1.124-6.364 2.897l-29.473 29.493c-13.46-7.335-30.702-5.324-42.078 6.05-6.708 6.708-10.398 15.624-10.392 25.107.006 9.469 3.701 18.364 10.392 25.036 6.918 6.917 16.004 10.374 25.09 10.374 9.082 0 18.164-3.456 25.073-10.364 6.701-6.682 10.396-15.576 10.402-25.045.004-6.05-1.503-11.866-4.332-17.028l26.535-26.553h31.129v122.631c.002 22.292-18.136 40.428-40.431 40.428zm-32.899-352.501c0 4.133-1.61 8.019-4.533 10.942-6.036 6.035-15.855 6.035-21.891 0-2.923-2.923-4.533-6.809-4.533-10.942s1.61-8.02 4.533-10.942c6.036-6.034 15.856-6.034 21.891 0 2.923 2.922 4.533 6.808 4.533 10.942zm-7.888 116.487c0 8.537-6.947 15.483-15.486 15.483-8.523 0-15.458-6.946-15.458-15.483 0-8.521 6.935-15.455 15.458-15.455 8.539 0 15.486 6.933 15.486 15.455zm7.888 116.523c-.003 4.121-1.609 7.991-4.533 10.906-6.036 6.034-15.856 6.035-21.901-.01-2.914-2.905-4.521-6.775-4.523-10.896-.003-4.135 1.607-8.024 4.533-10.95 6.035-6.033 15.855-6.034 21.889-.001.001.001.002.002.003.004 0 0 .001.001.001.001 2.925 2.926 4.534 6.813 4.531 10.946zm223.045.144-23.058 23.056h-106.655v-29.634h90.073c5.523 0 10-4.477 10-10v-55.218c0-5.523-4.477-10-10-10s-10 4.477-10 10v45.218h-80.073v-180.15h80.073v45.104c0 5.523 4.477 10 10 10s10-4.477 10-10v-55.104c0-5.523-4.477-10-10-10h-90.073v-29.662h106.652l23.061 23.081z"></path>
													<path d="m369.979 245.958c-5.523 0-10 4.477-10 10v.028c0 5.523 4.477 9.986 10 9.986s10-4.491 10-10.014-4.478-10-10-10z"></path>
												</svg>
											</span>
											<h4 className="u-text u-text-4">Firewalls</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					<section
						style={{
							backgroundImage: "linear-gradient(220deg,#db545a, #232b79 50%)",
						}}
						className="u-align-center u-clearfix u-grey-5 u-section-3"
						id="carousel_082c"
						data-aos="fade-in"
					>
						<div className="u-align-center u-clearfix u-sheet u-sheet-1">
							<h2 className=" text-white u-text u-text-default-lg u-text-default-md u-text-default-sm u-text-default-xl u-text-1">
								Our Offering Services
							</h2>
							<div
								className="u-border-2 u-border-palette-1-base u-shape u-shape-svg u-text-grey-5 u-shape-1"
								data-aos="fade-up"
							>
								<svg className="u-svg-link" viewBox="0 0 160 50">
									<use
										xmlnsXlink="http://www.w3.org/1999/xlink"
										xlinkHref="#svg-0c8e"
									></use>
								</svg>
								<svg
									className="u-svg-content"
									viewBox="-1 -1 162 52"
									x="0px"
									y="0px"
									id="svg-0c8e"
								>
									<path
										d="M133,26.7c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,22
	c11.2-7.8,20.6-8.1,32.2,0c11,7.6,19,8.5,31.3,0c11.6-8.1,22.4-7.7,33.5,0c11.4,8,20.3,8.3,32.2,0c11.6-8.1,19.2-8.1,30.8,0
	l-3.8,4.7C146.9,20.2,142.3,20.2,133,26.7z M133,10.8c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0
	c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,6.1c11.2-7.8,20.6-8.1,32.2,0c11,7.6,19,8.5,31.3,0C75.1-2,85.9-1.6,97,6.1
	c11.4,8,20.3,8.3,32.2,0C140.8-2,148.4-2,160,6.1l-3.8,4.7C146.9,4.3,142.3,4.3,133,10.8z M32.2,38c11,7.6,19,8.5,31.3,0
	c11.6-8.1,22.4-7.7,33.5,0c11.4,8,20.3,8.3,32.2,0c11.6-8.1,19.2-8.1,30.8,0l-3.8,4.7c-9.3-6.5-13.9-6.5-23.3,0
	c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,38
	C11.2,30.2,20.6,29.9,32.2,38z"
									></path>
								</svg>
							</div>
							<div
								className="u-align-center-sm u-align-center-xs u-list u-list-1"
								data-aos="slide-up"
							>
								<div className="u-repeater u-repeater-1">
									<div className="u-align-left u-container-style u-list-item u-repeater-item u-white u-list-item-1">
										<div className="u-container-layout u-similar-container u-container-layout-1">
											<h5 className="u-text u-text-2">
												END USING Computing<span></span>
											</h5>
											<p className="u-text u-text-3">
												Desktops, Laptops, AIO PCs, Tablets, Smart Devices, Thin
												Clients, Zero Clients etc
											</p>
											<div className="u-align-center u-image u-image-contain u-image-default u-image-1">
												<Image
													src={computing}
													alt=""
													width="928"
													height="449"
												/>
											</div>
										</div>
									</div>
									<div className="u-align-left u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-2">
										<div className="u-container-layout u-similar-container u-container-layout-2">
											<h5 className="u-text u-text-4"> ENTERPRISE Computing</h5>
											<p className="u-text u-text-5">
												&nbsp; Servers, NAS/SAN/Hybrid Storages, Tape Libraries,
												Backup &amp; Archiving solutions, Virtualization
												Solutions, Core Networking, Data Centers Designing &amp;
												Implementation&nbsp;
											</p>
											<div className="u-align-center u-image u-image-default u-image-2">
												<Image
													src={enterprise}
													alt=""
													width="486"
													height="237"
												/>
											</div>
										</div>
									</div>
									<div className="u-align-left u-container-style u-list-item u-repeater-item u-video-cover u-white u-list-item-3">
										<div className="u-container-layout u-similar-container u-container-layout-3">
											<h5 className="u-text u-text-6">SOFTWARE SOLUTION</h5>
											<p className="u-text u-text-7">
												&nbsp; Software designing as per requirement with
												consultancy.&nbsp;&nbsp;
											</p>
											<div className="u-align-center u-image u-image-default u-image-3">
												<Image src={software} alt="" width="450" height="382" />
											</div>
										</div>
									</div>
								</div>
							</div>
							<div
								className="u-image u-image-circle u-preserve-proportions u-image-4"
								alt=""
								data-image-width="800"
								data-image-height="800"
								data-aos="zoom-in"
							></div>
							<p
								style={{
									textAlign: "justify",
									fontSize: "18px",
									color: "white",
								}}
								data-aos="zoom-in"
							>
								USS Enterprises is committed to the provision of various
								Information & Communication Technology and other equipments
								Sales and services such as Hardware, software, Local area
								Network solutions & Optical fiber installations and
								configurations, Security Equipment’s Video Surveillance, Walk,
								Through Gates, HESCO Bags, Hand Held Detecting System, Explosive
								Detective, CCTV Solution, LED Walls, UPS, Generators, etc. The
								company has been in operation since 2012. The key personnel in
								the organization have a combined experience of more than 15
								years in the information & Communication Technology. We are able
								to supply and install a world renowned brand of below
								equipments.
							</p>
							<a
								href="#"
								className="u-btn u-btn-rectangle u-button-style u-color-scheme-summer-time u-color-style-multicolor-1 u-palette-2-base u-radius-0 u-btn-1"
							>
								Catch Us
							</a>
						</div>
					</section>
					<section
						className="u-align-center u-clearfix u-palette-1-base u-section-4"
						id="carousel_5f6d"
						data-aos="fade-in"
					>
						<div className="u-expanded-width u-image u-image-1">
							<Image src={swa} />
						</div>
						<div className="u-list u-list-1">
							<div className="u-repeater u-repeater-1" data-aos="slide-up">
								<div className="u-align-center u-container-style u-list-item u-repeater-item u-shape-round u-white u-list-item-1">
									<div className="u-container-layout u-similar-container u-valign-top u-container-layout-1">
										<div className="u-align-center u-container-style u-group u-palette-1-base u-radius-50 u-shape-round u-group-1">
											<div className="u-container-layout u-valign-middle u-container-layout-2">
												<h2 className="u-custom-font u-font-oswald u-text u-text-1">
													01
												</h2>
											</div>
										</div>
										<h5 className="u-text u-text-2">
											{" "}
											NETWORK &amp; POWER SOLUTION
										</h5>
										<p className="u-text u-text-grey-60 u-text-3">
											Firewalls, End User Security, Internet Management, WAN
											Optimization&nbsp;
										</p>
										<a
											href="https://nicepage.com/wordpress-themes"
											className="u-border-1 u-border-active-black u-border-hover-black u-border-palette-1-base u-btn u-button-style u-none u-text-active-grey-60 u-text-body-color u-text-hover-grey-60 u-btn-1"
										>
											learn more
										</a>
									</div>
								</div>
								<div className="u-align-center u-container-style u-list-item u-repeater-item u-shape-round u-white u-list-item-2">
									<div className="u-container-layout u-similar-container u-valign-top u-container-layout-3">
										<div className="u-align-center u-container-style u-group u-palette-1-base u-radius-50 u-shape-round u-video-cover u-group-2">
											<div className="u-container-layout u-valign-middle u-container-layout-4">
												<h2 className="u-custom-font u-font-oswald u-text u-text-4">
													02
												</h2>
											</div>
										</div>
										<h5 className="u-text u-text-5">securities solution</h5>
										<p className="u-text u-text-grey-60 u-text-6">
											&nbsp; CCTV &amp; Walkthrough gates
											Securitysolutions.&nbsp;&nbsp;
											<b>
												<span>
													technological tools and services that help protect
													organizations against cyber attacks
												</span>
											</b>
											&nbsp;
										</p>
										<a
											href="https://nicepage.com/website-mockup"
											className="u-border-1 u-border-active-black u-border-hover-black u-border-palette-1-base u-btn u-button-style u-none u-text-active-grey-60 u-text-body-color u-text-hover-grey-60 u-btn-2"
										>
											learn more
										</a>
									</div>
								</div>
								<div className="u-align-center u-container-style u-list-item u-repeater-item u-shape-round u-white u-list-item-3">
									<div className="u-container-layout u-similar-container u-valign-top u-container-layout-5">
										<div className="u-align-center u-container-style u-group u-palette-1-base u-radius-50 u-shape-round u-video-cover u-group-3">
											<div className="u-container-layout u-valign-middle u-container-layout-6">
												<h2 className="u-custom-font u-font-oswald u-text u-text-7">
													03
												</h2>
											</div>
										</div>
										<h5 className="u-text u-text-8">
											{" "}
											Services &amp; component solution
										</h5>
										<p className="u-text u-text-grey-60 u-text-9">
											<i>Service Level Agreements (SLA’s).&nbsp;</i>Local
											warranty Extensions.
										</p>
										<a
											href="https://nicepage.com/website-builder"
											className="u-border-1 u-border-active-black u-border-hover-black u-border-palette-1-base u-btn u-button-style u-none u-text-active-grey-60 u-text-body-color u-text-hover-grey-60 u-btn-3"
										>
											learn more
										</a>
									</div>
								</div>
								<div className="u-align-center u-container-style u-list-item u-repeater-item u-shape-round u-white u-list-item-3">
									<div className="u-container-layout u-similar-container u-valign-top u-container-layout-5">
										<div className="u-align-center u-container-style u-group u-palette-1-base u-radius-50 u-shape-round u-video-cover u-group-3">
											<div className="u-container-layout u-valign-middle u-container-layout-6">
												<h2 className="u-custom-font u-font-oswald u-text u-text-7">
													04
												</h2>
											</div>
										</div>
										<h5 className="u-text u-text-8">IT CONSULTANT</h5>
										<p className="u-text u-text-grey-60 u-text-12">
											Solution recommendations according to requirements with
											inspections
										</p>
										<a
											href="https://nicepage.com/k/dog-website-templates"
											className="u-border-1 u-border-active-black u-border-hover-black u-border-palette-1-base u-btn u-button-style u-none u-text-active-grey-60 u-text-body-color u-text-hover-grey-60 u-btn-3"
										>
											learn more
										</a>
									</div>
								</div>
							</div>
						</div>
					</section>
					<section
						className="u-clearfix u-grey-5 u-valign-middle-sm u-valign-middle-xs u-section-5"
						id="carousel_c9da"
						data-aos="fade-in"
					>
						<div className="u-expanded-width u-palette-1-dark-1 u-shape u-shape-rectangle u-shape-1"></div>
						<div className="u-palette-1-light-2 u-shape u-shape-rectangle u-shape-2"></div>
						<div className="u-shape u-shape-rectangle u-white u-shape-3"></div>
						<div className="u-image u-image-1">
							<Image src={min} width="1200" height="1048" />
						</div>
						<div className="u-align-left u-container-style u-expanded-width-sm u-expanded-width-xs u-group u-similar-fill u-group-1">
							<div className="u-container-layout u-container-layout-1">
								<h2 className="u-align-center u-text u-text-1">
									{" "}
									Multimedia &amp; Digital Platform
								</h2>
								<p className="u-align-center u-large-text u-text u-text-variant u-text-2">
									Multimedia projectors allow for presentations that can be used
									for work functions, classroom instruction or enjoyment of
									films and television at home.
								</p>
								<p className="u-align-center u-text u-text-3">
									Smart Conference room | Smart Labs | Projectors |LEDs | Sound
									Systems&nbsp;
								</p>
								<a
									href="https://nicepage.com/c/sports-html-templates"
									className="u-active-palette-1-light-1 u-border-none u-btn u-button-style u-color-scheme-summer-time u-color-style-multicolor-1 u-hover-palette-1-light-1 u-palette-1-base u-btn-1"
								>
									Learn more
								</a>
							</div>
						</div>
					</section>

					<section
						data-aos="fade-in"
						style={{ backgroundColor: "#282c7c", height: "600px" }}
					>
						<br></br>
						<h2 style={{ textAlign: "center", color: "white" }}>
							Smart Attendance Solutions.
						</h2>
						<p style={{ textAlign: "center", color: "white" }}>
							Wall mount, ATM Kiosk, Short range, Long range RFID’s, Finger
							Print, Face Detections solutions,<br></br>Walk Through Floor Stand
							Single & Multiple Module.
						</p>
						<div className="u-align-center u-image u-image-round u-radius-10 u-image-1">
							{" "}
							<Image
								data-image-width="764"
								data-image-height="447"
								src={Attendence}
							/>
						</div>
					</section>

					<section
						className="u-align-center u-clearfix u-white u-section-7"
						id="carousel_d7d1"
						data-aos="fade-in"
					>
						<h2 className="u-text u-text-default u-text-1">
							{" "}
							Technology Of The Future
						</h2>
						<p className="u-text u-text-default u-text-2">
							<b>
								<i>Printing &amp; Photocopying Devices.</i>
							</b>
						</p>
						<div className="u-border-2 u-border-palette-1-base u-shape u-shape-svg u-text-grey-5 u-shape-1">
							<svg className="u-svg-link" viewBox="0 0 160 50">
								<use
									xmlnsXlink="http://www.w3.org/1999/xlink"
									xlinkHref="#svg-78f4"
								></use>
							</svg>
							<svg
								className="u-svg-content"
								viewBox="-1 -1 162 52"
								x="0px"
								y="0px"
								id="svg-78f4"
							>
								<path
									d="M133,26.7c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,22
	c11.2-7.8,20.6-8.1,32.2,0c11,7.6,19,8.5,31.3,0c11.6-8.1,22.4-7.7,33.5,0c11.4,8,20.3,8.3,32.2,0c11.6-8.1,19.2-8.1,30.8,0
	l-3.8,4.7C146.9,20.2,142.3,20.2,133,26.7z M133,10.8c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0
	c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,6.1c11.2-7.8,20.6-8.1,32.2,0c11,7.6,19,8.5,31.3,0C75.1-2,85.9-1.6,97,6.1
	c11.4,8,20.3,8.3,32.2,0C140.8-2,148.4-2,160,6.1l-3.8,4.7C146.9,4.3,142.3,4.3,133,10.8z M32.2,38c11,7.6,19,8.5,31.3,0
	c11.6-8.1,22.4-7.7,33.5,0c11.4,8,20.3,8.3,32.2,0c11.6-8.1,19.2-8.1,30.8,0l-3.8,4.7c-9.3-6.5-13.9-6.5-23.3,0
	c-13.9,9.7-25.8,9.7-39.8,0c-9.1-6.3-16.8-6.3-25.9,0c-13.8,9.6-25.1,9.6-38.9,0c-9.2-6.4-15.4-6.4-24.6,0L0,38
	C11.2,30.2,20.6,29.9,32.2,38z"
								></path>
							</svg>
						</div>
					</section>

					<section
						className="u-align-center u-clearfix u-white u-section-8"
						id="carousel_5def"
						data-aos="fade-in"
					>
						<div className="u-clearfix u-expanded-width u-gutter-30 u-layout-wrap u-layout-wrap-1">
							<div className="u-layout">
								<div className="u-layout-row">
									<div className="u-container-style u-expand-resize u-layout-cell u-left-cell u-size-28 u-layout-cell-1">
										<div className="u-container-layout">
											<div className="u-align-left u-expanded-width-sm u-expanded-width-xs u-palette-1-base u-shape u-shape-2"></div>
											<div className="u-align-center u-image u-image-round u-radius-10 u-image-1">
												{" "}
												<Image
													data-image-width="764"
													data-image-height="447"
													src={Printer}
												/>
											</div>
										</div>
									</div>
									<div
										className="u-container-style u-layout-cell u-right-cell u-size-32 u-layout-cell-2"
										data-aos="zoom-in"
									>
										<div className="u-container-layout u-valign-bottom-sm u-valign-bottom-xs u-valign-middle-lg u-valign-middle-md u-valign-middle-xl u-container-layout-2">
											<h2 className="u-align-center ">Printers</h2>
											<h3
												style={{
													textAlign: "center",
													color: "#eda80e",
													fontWeight: "bold",
													fontSize: "20px",
												}}
											>
												Best Printers USS Enterprises
											</h3>
											<p style={{ textAlign: "justify" }}>
												Are you looking to buy printers for your organization,
												<b>school or company?</b>
												We sell high quality printers to different IT industry
												with best prices and packages. Printers include{" "}
												<b>
													Multi Function Printers, Inkjet Printers, Laser
													Printers etc
												</b>
												. Dont waste your time on other plateforms contact us
												now we will assist you in a very quick way.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div
							style={{ backgroundColor: "#282c7c" }}
							className="u-clearfix u-expanded-width u-gutter-30 u-layout-wrap u-layout-wrap-1"
						>
							<div className="u-layout">
								<div className="u-layout-row" data-aos="zoom-in">
									<div className="u-container-style u-layout-cell u-right-cell u-size-32 u-layout-cell-2">
										<div className="u-container-layout u-valign-bottom-sm u-valign-bottom-xs u-valign-middle-lg u-valign-middle-md u-valign-middle-xl u-container-layout-2">
											<h2 className="u-align-center text-white ">
												AIO-Scanners
											</h2>
											<h3
												style={{
													textAlign: "center",
													color: "#eda80e",
													fontWeight: "bold",
													fontSize: "20px",
												}}
											>
												Best AIO-Scanners USS Enterprises
											</h3>

											<p
												className=" text-white "
												style={{ textAlign: "justify" }}
											>
												Are you looking to buy all in one scanners for your
												shop? We sell high quality all in one scanners with best
												prices and packages. These scanners are Easy to add
												products to lines using a mobile scanner. Its a handy
												tool for the user to scan product quickly using Barcode
												or QRCode. contact us now we will assist you in a very
												quick way.
											</p>
										</div>
									</div>
									<div className="u-container-style u-expand-resize u-layout-cell u-left-cell u-size-28 u-layout-cell-1">
										<div className="u-container-layout">
											<div className="u-align-left u-expanded-width-sm u-expanded-width-xs u-palette-1-base u-shape u-shape-2"></div>
											<br></br>
											<br></br>
											<div
												style={{ width: "90%", height: "50%" }}
												className="u-align-center u-image u-image-round u-radius-10 u-image-1 "
											>
												{" "}
												<Image
													data-image-width="764"
													data-image-height="447"
													src={AIO}
												/>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div className="u-clearfix u-expanded-width u-gutter-30 u-layout-wrap u-layout-wrap-1">
							<div className="u-layout">
								<div className="u-layout-row" data-aos="zoom-in">
									<div className="u-container-style u-expand-resize u-layout-cell u-left-cell u-size-28 u-layout-cell-1">
										<div className="u-container-layout">
											<div className="u-align-left u-expanded-width-sm u-expanded-width-xs u-palette-1-base u-shape u-shape-2"></div>
											<div className="u-align-center u-image u-image-round u-radius-10 u-image-1">
												{" "}
												<Image
													data-image-width="764"
													data-image-height="447"
													src={PhotoMachine}
												/>
											</div>
										</div>
									</div>
									<div className="u-container-style u-layout-cell u-right-cell u-size-32 u-layout-cell-2">
										<div className="u-container-layout u-valign-bottom-sm u-valign-bottom-xs u-valign-middle-lg u-valign-middle-md u-valign-middle-xl u-container-layout-2">
											<h2 className="u-align-center ">
												Heavy Duty Photocopiers
											</h2>
											<h3
												style={{
													textAlign: "center",
													color: "#eda80e",
													fontWeight: "bold",
													fontSize: "20px",
												}}
											>
												Best Heavy Duty Photocopiers USS Enterprises
											</h3>

											<p style={{ textAlign: "justify" }}>
												Are you looking to buy photocopier machine for your
												bussiness and want to increase your bussiness revenue?
												We sell high quality photocopier machine with best
												prices and packages. These machines have highly
												functionalites with color and fast printing services.
												contact us now we will assist you in a very quick way.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div className="u-clearfix u-sheet u-sheet-1">
							<div
								style={{ backgroundColor: "#282c7c" }}
								className="u-clearfix u-expanded-width u-gutter-30 u-layout-wrap u-layout-wrap-1"
							>
								<div className="u-layout">
									<div className="u-layout-row" data-aos="zoom-in">
										<div className="u-container-style u-expand-resize u-layout-cell u-left-cell u-size-28 u-layout-cell-1">
											<div className="u-container-layout">
												<div className="u-align-left u-expanded-width-sm u-expanded-width-xs u-palette-1-base u-shape u-shape-2"></div>
												<div className="u-align-center u-image u-image-round u-radius-10 u-image-1">
													{" "}
													<br></br>
													<br></br>
													<Image
														data-image-width="764"
														data-image-height="447"
														src={Solor}
													/>
												</div>
											</div>
										</div>
										<div className="u-container-style u-layout-cell u-right-cell u-size-32 u-layout-cell-2">
											<div className="u-container-layout u-valign-bottom-sm u-valign-bottom-xs u-valign-middle-lg u-valign-middle-md u-valign-middle-xl u-container-layout-2">
												<h2 className="u-align-center text-white">
													Alternate Energy solution
												</h2>
												<h3
													style={{
														textAlign: "center",
														color: "#eda80e",
														fontWeight: "bold",
														fontSize: "20px",
													}}
												>
													Best Alternate Energy solution USS Enterprises
												</h3>

												<p
													style={{ fontWeight: "lighter" }}
													className="u-align-justify text-white "
												>
													We have the best alernate energy solution for you.
													These alternative energy solutions include&nbsp;
													<b>
														solar photovoltaic energy, solar thermal energy,
														wind energy, hydroelectric energy and biomass energy
													</b>
													&nbsp;to name a few. The energy from these alternative
													energy solutions is derived from naturally-occurring
													sources that can be constantly replenished.
												</p>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div className="u-expanded-width u-list u-list-1">
								<div className="u-repeater u-repeater-1" data-aos="zoom-in">
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-valign-top-sm u-valign-top-xs u-container-layout-3">
											<span className="u-align-center-sm u-align-center-xs u-border-2 u-border-palette-1-base u-file-icon u-icon u-icon-circle u-text-palette-1-base u-icon-1">
												<div>
													<Image src={Grid} alt="" />
												</div>
											</span>
											<h3 className="u-text u-text-3">On Grid, Off Grid</h3>
											<p className="u-text u-text-4">
												<b>
													On-grid system is one in which the solar power system
													is connected to the utilitys power grid
												</b>
												&nbsp;while being off-grid means the system works
												independently&nbsp;
											</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-valign-top-sm u-valign-top-xs u-container-layout-4">
											<span className="u-align-center-sm u-align-center-xs u-border-2 u-border-palette-1-base u-file-icon u-icon u-icon-circle u-text-palette-1-base u-icon-2">
												<div>
													<Image src={Energy} alt="" />
												</div>
											</span>
											<h3 className="u-text u-text-5">Hybrid Solar Energy</h3>
											<p className="u-text u-text-6">
												hybrid solar system is&nbsp;
												<b>grid-tied with battery storage</b>. They come with a
												special smart inverter that can transmit direct current
												(DC) power to and from your batteries
											</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-valign-top-sm u-valign-top-xs u-container-layout-5">
											<span className="u-align-center-sm u-align-center-xs u-border-2 u-border-palette-1-base u-file-icon u-icon u-icon-circle u-text-palette-1-base u-icon-3">
												<div>
													<Image src={UPS} alt="" />
												</div>
											</span>
											<h3 className="u-text u-text-7">UPS</h3>
											<p className="u-text u-text-8">
												An uninterruptible power supply (UPS) is&nbsp;
												<b>
													a device that allows a computer to keep running for at
													least a short time when incoming power is interrupted
												</b>
											</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-valign-top-sm u-valign-top-xs u-container-layout-6">
											<span className="u-align-center-sm u-align-center-xs u-border-2 u-border-palette-1-base u-file-icon u-icon u-icon-circle u-icon-4">
												<div>
													<Image src={Generator} alt="" />
												</div>
											</span>
											<h3 className="u-text u-text-9">Generators</h3>
											<p className="u-text u-text-10">
												Electric generator is a device which is used to&nbsp;
												<b>produce electric energy</b>, which can be stored in
												batteries or can be directly supplied to the homes,
												shops, offices, etc
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					<section
						className="u-align-center u-clearfix u-section-9"
						id="sec-96e6"
						data-aos="fade-in"
					>
						<div className="u-align-center u-clearfix u-sheet u-sheet-1">
							<h2 className="u-text u-text-default u-text-1">Want To Buy?</h2>
							<p className="u-text u-text-2">
								If you are looking for the above services contact us now
							</p>
							<a
								href="tel:+92-21-34390018"
								className="u-active-white u-border-2 u-border-hover-white u-border-white u-btn u-button-style u-hover-white u-palette-1-base u-text-active-black u-text-body-alt-color u-text-hover-palette-1-base u-btn-1"
							>
								Call Now
							</a>
						</div>
					</section>
					<section
						className="u-clearfix u-section-10"
						id="carousel_d06f"
						data-aos="fade-in"
					>
						<div className="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
							<div className="u-gutter-0 u-layout">
								<div className="u-layout-row" data-aos="zoom-in">
									<div className="u-container-style u-layout-cell u-palette-1-base u-size-30 u-layout-cell-1">
										<div className="u-container-layout u-valign-middle u-container-layout-1">
											<h5 className="u-custom-font u-font-montserrat u-text u-text-body-alt-color u-text-1">
												What We Do
											</h5>
											<p className="u-align-justify u-text u-text-body-alt-color u-text-2">
												&nbsp; USS Enterprises is one of the fastest emerging IT
												Solution provider serving in IT industry since 2015 with
												a wide range of our{" "}
												<b>
													<i>“Products and Services Portfolio” </i>
												</b>
												covering every end to end requirement in IT
												Infrastructure. &nbsp; We believe in working as
												technology partner and solution provider for our
												clientele with an experienced and well qualified team of
												professionals and technology specialists. The key to our
												success is our Customer Oriented policies, our belief in
												Consultative Selling and the top of the line Support and
												Post Sales Services to our valued customers.
												<br />
												<br />
												&nbsp; Our Core values which form the basis of our
												business operations and our corporate social
												responsibility are&nbsp;&nbsp;
											</p>
										</div>
									</div>
									<div className="u-align-left u-container-style u-layout-cell u-size-30 u-layout-cell-2">
										<div className="u-container-layout u-valign-middle u-container-layout-2">
											<div
												className="u-align-center-sm u-align-center-xs u-image u-image-circle u-image-contain u-image-1"
												alt=""
												data-image-width="241"
												data-image-height="192"
											></div>
											<p className="u-text u-text-black u-text-3">
												{" "}
												Article evident arrived express highest men did boy.
												Mistress sensible entirely am so. Quick can manor smart
												money hopes worth too. Comfort produce husband boy her
												had hearing. Law others theirs passed but wishes. You
												day real less till dear read.
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					<section
						className="u-clearfix u-section-11"
						data-aos="slide-up"
						id="sec-69dc"
					>
						<div className="u-clearfix u-sheet u-sheet-1">
							<div className="u-expanded-width u-list u-list-1">
								<div className="u-repeater u-repeater-1">
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-1">
											<span className="u-file-icon u-icon u-icon-circle u-palette-1-base u-text-white u-icon-1">
												<Image src={Icon} alt="" />
											</span>
											<h3 className="u-text u-text-1">
												Committed with dedication.
											</h3>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-2">
											<span className="u-file-icon u-icon u-icon-circle u-palette-1-base u-text-white u-icon-2">
												<Image src={Icon} alt="" />
											</span>
											<h3 className="u-text u-text-2">
												&nbsp;Teamwork &amp; Synchronization.
											</h3>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-3">
											<span className="u-file-icon u-icon u-icon-circle u-palette-1-base u-text-white u-icon-3">
												<Image src={Icon} alt="" />
											</span>
											<h3 className="u-text u-text-3">
												Compliance professionally.
											</h3>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-4">
											<span className="u-file-icon u-icon u-icon-circle u-palette-1-base u-text-white u-icon-4">
												<Image src={Icon} alt="" />
											</span>
											<h3 className="u-text u-text-4">
												&nbsp;Best Recommendations.{" "}
											</h3>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					<CEO />
					<section
						className="u-align-center u-clearfix u-white u-section-13"
						id="carousel_fb5a"
						data-aos="fade-in"
					>
						<div className="u-clearfix u-sheet u-sheet-1" data-aos="slide-up">
							<h2 className="u-custom-font u-font-montserrat u-text u-text-default u-text-1">
								Our Core Alliances
							</h2>
							<Swiper
								id="carousel-8627"
								slidesPerView={3}
								spaceBetween={30}
								freeMode={true}
								pagination={{
									clickable: true,
								}}
								modules={[FreeMode, Pagination]}
								className="u-carousel u-expanded-width u-slider u-slider-1"
							>
								<SwiperSlide>
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt1}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt2}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt3}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt4}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt5}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt6}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
								<SwiperSlide>
									{" "}
									<div className="u-image u-image-contain u-image-default u-preserve-proportions u-image-5 ">
										<Image
											src={Clentt7}
											alt=""
											data-image-width="341"
											data-image-height="123"
										/>
									</div>
								</SwiperSlide>
							</Swiper>
							<a
								href=""
								className="u-btn u-btn-rectangle u-button-style u-palette-1-light-1 u-btn-1"
							>
								learn more
							</a>
						</div>
					</section>
					<Clients />
					<section
						className="u-align-center u-black u-clearfix u-section-15"
						id="sec-4a71"
						data-aos="fade-in"
					>
						<div className="u-clearfix u-sheet u-valign-middle-md u-valign-middle-sm u-valign-middle-xs u-sheet-1">
							<div className="u-expanded-width u-list u-list-1">
								<div className="u-repeater u-repeater-1">
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-1">
											<h1
												style={{ color: "#eda80e" }}
												data-animation-name="counter"
												data-animation-event="scroll"
												data-animation-duration="3000"
											>
												100
											</h1>
											<p className="u-text u-text-2">Project</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-2">
											<h1
												style={{ color: "#eda80e" }}
												data-animation-name="counter"
												data-animation-event="scroll"
												data-animation-duration="3000"
											>
												45
											</h1>
											<p className="u-text u-text-4">Clients</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-3">
											<h1
												style={{ color: "#eda80e" }}
												data-animation-name="counter"
												data-animation-event="scroll"
												data-animation-duration="3000"
											>
												20
											</h1>
											<p className="u-text u-text-6">Awards</p>
										</div>
									</div>
									<div className="u-align-center u-container-style u-list-item u-repeater-item">
										<div className="u-container-layout u-similar-container u-container-layout-4">
											<h1
												style={{ color: "#eda80e" }}
												data-animation-name="counter"
												data-animation-event="scroll"
												data-animation-duration="3000"
											>
												10
											</h1>
											<p className="u-text u-text-8">Our Team</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					<ContactForm />
				</div>
			)}
		</div>
	);
}
